version: "3"
services:
  celery:
    image: eeacms/celery
    environment:
      TZ: "Europe/Copenhagen"
      CELERY_BROKER_URL: "amqp://admin:admin@rabbit"
      CELERY_BACKEND_URL: "redis://redis"
      ADDONS: "nltk==3.4"
      TASKS: |
        import nltk
        nltk.download('punkt')

        @message_handler('x_queue')
        def handle_x(body):
          tokens = nltk.word_tokenize(body)
          print(tokens)
          return tokens

        @message_handler('y_queue')
        def handle_y(body):
          print("Y - %s" % body)
    depends_on:
    - redis
    - rabbit

  redis:
    image: redis:5

  rabbit:
    image: rabbitmq:management-alpine
    ports:
    - "15672:15672"
    environment:
      TZ: Europe/Copenhagen
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
