version: "3"
services:
  celery:
    image: eeacms/celery
    ports:
    - "5555:5555"
    environment:
      TZ: "Europe/Copenhagen"
      CELERY_QUEUE: "x_queue,y_queue"
      CELERY_BROKER_URL: "amqp://admin:admin@rabbit"
      CELERY_BACKEND_URL: "redis://redis"
      CELERY_TASKS: |
        @message_handler('x_queue')
        def handle_x(body):
          print("X - %s" % body)
        @message_handler('y_queue')
        def handle_y(body):
          print("Y - %s" % body)
    depends_on:
    - redis
    - rabbit

  redis:
    image: redis:5

  rabbit:
    image: rabbitmq:management-alpine
    ports:
    - "15672:15672"
    environment:
      TZ: Europe/Copenhagen
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
