version: "3"
services:
  celery:
    image: eeacms/celery
    environment:
      TZ: "Europe/Copenhagen"
      CELERY_BROKER_URL: "amqp://admin:admin@rabbit"
      CELERY_BACKEND_URL: "redis://redis"
      REQUIREMENTS: |
        nltk
        requests
      CONSTRAINTS: |
        nltk==3.4
        requests==2.21.0
      TASKS: |
        import requests
        import nltk
        nltk.download('punkt')

        @message_handler('nltk_queue')
        def handle_nltk(body):
          tokens = nltk.word_tokenize(body)
          print(tokens)
          return tokens

        @message_handler('req_queue')
        def handle_req(url):
          res = requests.get(url)
          status = res.status_code
          print("Got %s status code while calling %s" % (status, url))
          return status
    depends_on:
    - redis
    - rabbit

  redis:
    image: redis:5

  rabbit:
    image: rabbitmq:management-alpine
    ports:
    - "15672:15672"
    environment:
      TZ: Europe/Copenhagen
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
